### ISSUE TITLE
Seprate Community HUB parent from camunda-release-parent

### ISSUE THREAD

**Issue by zambrovski** [camunda-community-hub/community-hub-release-parent#9]
Hi Rin,

I would like to propose to de-couple the Camunda HUB release parent from (product) Camunda Release parent. In doing so, the changes of product development are not influencing the community changes.

I believe it is a little error-prone to inherit versions of Maven plugins and some settings over two levels. I don't see any reason, why `community-hub-release-parent` should rely on settings defined for the product release parent...

What do you think?

Cheers,

Simon

**Comment by zambrovski** [comment]
Let me give you even more practical context on this:

`camunda-release-parent` was defining artifact handling inside the JAR creation by using a feature that has been deprecated. To maintain backward-compatibility the version of Maven JAR plugin is pinned to 2.6 (last version before deprecation in 3.0.0, current version is 3.2.0). 

Since `camunda-release-parent` is not only defining the version but also some default configuration using the deprecated feature, there is no way to overwrite (subtract) this property in the downstream poms of the `community-hub-release-parent` or in a community extension...

To be up-to-date with the versions I already tried to support JDK 17 in one of the extensions (process-test-coverage) and hat to revoke it, because of the fact that the regressions tests are failing to run using JAR plugin 2.6...

**Comment by celanthe** [comment]
Hi @zambrovski! That sounds great. I look forward to it! :)

**Comment by celanthe** [comment]
Update on this, I've assigned @akeller temporarily to this issue for future triaging purposes. :)

**Comment by berndruecker** [comment]
@zambrovski Can you have a look at the latest main branch briefly? I removed the parent dependency with https://github.com/camunda-community-hub/community-hub-release-parent/commit/24daadcbd040cb17cfb4fb94c1cb4ed12fedfeae - anything missing from your end?

**Comment by zambrovski** [comment]
Will do

**Comment by berndruecker** [comment]
I still have some wired issues with authentication and actually do not yet understand how the Sonatype/NExus login works at the moment. Thinking about this I wondered if we should maybe even go more puristic with the parent and include as less as possible, so basically only what we need for distribution management. That could be probably less than we currently have. WDYT @zambrovski ?
